<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>管理平台 | <?echo $title;?></title>

    <!-- Bootstrap -->
    <link href="/bower_components/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/bower_components/gentelella/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/bower_components/gentelella/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="/bower_components/gentelella/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
    <!-- Switchery -->
    <link href="/bower_components/gentelella/vendors/switchery/dist/switchery.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/bower_components/gentelella/build/css/custom.min.css" rel="stylesheet">
    <!-- Dropzone.js -->
    <link href="/bower_components/gentelella/vendors/dropzone/dist/min/dropzone.min.css" rel="stylesheet">

    <link href="/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

    <link media="all" rel="stylesheet" type="text/css" href="/bower_components/simditor/styles/simditor.css" />

    <link href="/css/thewbb.css" rel="stylesheet">

    <script src="https://cdn.bootcss.com/vue/2.5.13/vue.js"></script>
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <?echo $current->sidebarTemplate()?>
        <?echo $current->headerTemplate()?>

        <!-- page content -->
        <div class="right_col" role="main">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>新建<small></small></h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content" >
                        <br>
                        <form id="demo-form2" data-parsley-validate="" action="" class="form-horizontal form-label-left" novalidate="" method="post">
                            <?foreach($fields as $key => $field){
                                switch($field["type"]){
                                    case "file":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div><?echo $field["data"]?></div>
                                                <div id="-<?echo $key?>" action="/file/upload" class="dropzone"></div>
                                                <input type="hidden" id="post-<?echo $key?>" name="post-<?echo $key?>" value="<?echo $_POST["post-$key"]?>">
                                            </div>
                                        </div>
                                        <?break;
                                    case "select":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">

                                                <select class="form-control col-md-7 col-xs-12" name="post-<?echo $key?>" <?echo $field["readonly"]?"readonly":""?>>
                                                    <?foreach($field["options"] as $key => $option){?>
                                                        <option value="<?echo $key?>" <?echo $field["data"] == $key?"selected":""?>><?echo $option?></option>
                                                    <?}?>
                                                </select>
                                            </div>
                                        </div>
                                        <?break;
                                    case "boolean":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12" style="padding-top: 5px;">
                                                <input type="checkbox" class="js-switch" id="post-<?echo $key?>" <?echo $field["readonly"]?"readonly":""?> name="post-<?echo $key?>" <?echo $field["data"] == 1?"checked":""?> />
                                            </div>
                                        </div>
                                        <?break;
                                    case "many_to_one":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div style="float: left;width: 70%;">
                                                    <?list($table_name, $field_name) = explode(".", $key);?>
                                                    <input class="form-control" style="height: 32px;" type="text" id="post-<?echo $key?>-data" name="post-<?echo $key?>-data" readonly
                                                           value="<?echo $_POST["post-{$table_name}_{$field_name}-data"]?>">
                                                    <input type="hidden" id="post-<?echo $key?>" name="post-<?echo $key?>" value="<?echo $_POST["post-{$table_name}_{$field_name}"]?>">
                                                    <input type="hidden" id="post-<?echo $key?>-refer" name="post-<?echo $key?>-refer" value="<?echo $field["id"]?>">
                                                    <input type="hidden" id="post-<?echo $key?>-show" name="post-<?echo $key?>-show" value="<?echo $field_name;?>">
                                                </div>
                                                <div style="float: left;">
                                                    <a id="post-<?echo $key?>-remove" class="glyphicon glyphicon-remove btn remove_many_to_one"style="pointer-events: auto; margin-top: -2px;"></a>
                                                    <button id="post-<?echo $key?>" name="post-<?echo $key?>" style="height: 32px;margin-left: 16px;" class="btn btn-default many_to_one">选择</button>
                                                    <input type="hidden" id="post-<?echo $key?>-url" value="<?echo $field["url"]?>">
                                                </div>
                                            </div>
                                        </div>
                                        <?break;
                                    case "one_to_many":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="form-group col-md-9 col-sm-9 col-xs-12" id="post-<?echo $key?>">
                                                <input type="hidden" name="post-<?echo $key?>" v-model="items_json" >
                                                <table>
                                                    <thead>
                                                        <tr>
                                                            <?foreach($field["columns"] as $column_key => $column){?>
                                                                <td style="min-width:100px;text-align: center;"><?echo $column["label"]?></td>
                                                            <?}?>
                                                            <td><button v-on:click="addItem()" type="button">添加</button></td>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr v-for="item in items">
                                                            <?foreach($field["columns"] as $column_key => $column){?>
                                                                <td><input type="text" width="100%;" v-model="item.<?echo $column_key?>"></td>
                                                            <?}?>
                                                            <td><button v-on:click="removeItem(item)" type="button">删除</button></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                            <script>
                                                var app_<?echo $key?> = new Vue({
                                                    el: "#post-<?echo $key?>",
                                                    data: {
                                                        items: [],
                                                    },
                                                    computed: {
                                                        items_json: function () {
                                                            return JSON.stringify(this._data);
                                                        },
                                                    },
                                                    methods:{
                                                        addItem:function(){
                                                            console.log("add action");

                                                            this.items.push({
                                                                <?foreach($field["columns"] as $column_key => $column){
                                                                    echo $column_key.":null,";
                                                                }?>
                                                            });

                                                        },
                                                        removeItem:function(item){
                                                            console.log("remove action");
                                                            if(confirm('确实要删除吗?')){
                                                                for(var i = 0; i < this.items.length; i++){
                                                                    if(this.items[i] == item){
                                                                        this.items.splice(i,1);
                                                                        break;
                                                                    }
                                                                }
                                                            }
                                                            event.preventDefault();
                                                            return false;
                                                        }
                                                    }
                                                });
                                            </script>
                                        </div>

                                        <?break;
                                    case "datetime":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12" style="padding-top: 5px;">
                                                <input type="text" name="post-<?echo $key?>" <?echo $field["readonly"]?"readonly":""?> id="post-<?echo $key?>" class="form-control datetime" value="<?echo empty($_POST["post-$key"])? $field['data']:$_POST["post-$key"]?>"/>

                                            </div>
                                        </div>
                                        <?break;
                                    case "richedit":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <textarea type="text" id="post-<?echo $key?>" <?echo $field["readonly"]?"readonly":""?> name="post-<?echo $key?>" value="" required="required" class="form-control col-md-7 col-xs-12 simditor"></textarea>
                                            </div>
                                        </div>
                                        <?break;
                                    case "hidden":?>
                                        <input type="hidden" id="post-<?echo $key?>" name="post-<?echo $key?>" value="<?echo empty($_POST["post-$key"])? $field['data']:$_POST["post-$key"]?>"
                                               required="required" class="form-control col-md-7 col-xs-12">
                                        <?break;
                                    default:?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="post-<?echo $key?>" <?echo $field["readonly"]?"readonly":""?> name="post-<?echo $key?>" value="<?echo empty($_POST["post-$key"])? $field['data']:$_POST["post-$key"]?>" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    <?}
                            }?>
                            <div class="ln_solid"></div>
                            <input type="hidden" name="<?echo $this->security->getTokenKey() ?>" value="<?echo $this->security->getToken() ?>"/>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <a href="<?echo "/$current->controller/list"?>" class="btn btn-default" type="button">取消</a>
                                    <button class="btn btn-primary" type="reset">重置</button>
                                    <button type="submit" class="btn btn-success">提交</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->
        <?echo $footerTemplate?>
    </div>
</div>
<div id="show_mask_parent" style="z-index: 999;position: fixed; display: none;width: 90%;height: 90%;top: 5%;left: 5%;">
    <img id="child-close" src="/img/close.png" style="position: fixed;top: 7%;right: 8%;width: 32px;height: 32px;">
    <div  id="show_mask" style="width: 100%;height: 100%;"></div>
</div>
<!-- jQuery -->
<script src="/bower_components/gentelella/vendors/jquery/dist/jquery.min.js"></script>
<!-- Dropzone.js -->
<script src="/bower_components/gentelella/vendors/dropzone/dist/min/dropzone.min.js"></script>
<!-- Bootstrap -->
<script src="/bower_components/gentelella/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Switchery -->
<script src="/bower_components/gentelella/vendors/switchery/dist/switchery.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/gentelella/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="/bower_components/gentelella/vendors/nprogress/nprogress.js"></script>
<!-- jQuery custom content scroller -->
<script src="/bower_components/gentelella/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>

<script src="/bower_components/gentelella/vendors/iCheck/icheck.min.js"></script>
<!-- Custom Theme Scripts -->
<script src="/bower_components/gentelella/build/js/custom.min.js"></script>

<script src="/bower_components/moment/min/moment-with-locales.min.js"></script>

<script src="/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>

<script type="text/javascript" src="/bower_components/simple-module/lib/module.js"></script>
<script type="text/javascript" src="/bower_components/simple-uploader/lib/uploader.js"></script>
<script type="text/javascript" src="/bower_components/simple-hotkeys/lib/hotkeys.js"></script>
<script type="text/javascript" src="/bower_components/simditor/lib/simditor.js"></script>

<script src="/js/thewbb_alert.js"></script>
<script>
    Dropzone.autoDiscover = false;
    $(".datetime").datetimepicker({format:'YYYY-MM-DD HH:mm', locale:'zh-cn'});

    
    var editor, toolbar;
    Simditor.locale = 'zh-CN';
    toolbar = ['title', 'bold', 'italic', 'underline', 'strikethrough', 'fontScale', 'color', '|', 'ol', 'ul', 'blockquote', 'code', 'table', '|', 'link', 'image', 'hr', '|', 'indent', 'outdent', 'alignment'];

    editor = new Simditor({
        textarea: $('.simditor'),
        placeholder: '这里输入文字...',
        toolbar: toolbar,
        pasteImage: true,
        defaultImage: '/img/logo.png',
        upload: {
            url: '/file/simditorUpload'
        }
    });

    $(".dropzone").each(function(){
        var id = $(this).attr("id");
        $(this).dropzone({
            url: "/file/uploadReturnUrl",
            maxFiles: 1,
            success : function(file, response){
                $("#post"+id).val(response);
            }
        });
    });

    $(".many_to_one").click(function(event){
        var id = $(this).attr("id");
        var url_id = "#" + id + "-url";
        var show_id = "#" + id + "-show";

        var url = $(url_id.replace("\.", "\\\.")).val();
        var show = $(show_id.replace("\.", "\\\.")).val();

        url += "&key="+id+"&data="+id+"-data&show=" + show;
        console.log(url);
        $("#show_mask").html('<iframe style="width: 100%; height: 100%;" src="' + url + '"></iframe>');
        $("#show_mask_parent").css("display", "block");
        $("#child-close").css("display", "block");
        event.preventDefault();
    });

    $(".remove_many_to_one").click(function(event){
        var id = $(this).attr("id").replace("-remove", "");
        var data_id = id + "-data";
        $("#" + id.replace("\.", "\\\.")).attr("value", "");
        $("#" + data_id.replace("\.", "\\\.")).attr("value", "");
        event.preventDefault();
    });

    $("#child-close").click(function(event){
        $("#show_mask").html('');
        $("#show_mask_parent").css("display", "none");
        $("#child-close").css("display", "none");
    });

</script>

</body>
</html>