<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <?echo $user["username"]?>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="/editprofile"> 修改个人信息</a></li>
                        <li>
                            <a href="javascript:;" style="display: none;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;" style="display: none;">Help</a></li>
                        <li><a href="/logout"><i class="fa fa-sign-out pull-right"></i> 退出</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<?php $this->flashSession->output() ?>
<!-- /top navigation -->